### ISSUE TITLE
Стартовая линия

### ISSUE THREAD

**Issue by paulin-mipt** [AnnaSavinova/PromProg_Race_CardRedactor#5]
Без комментариев. Пока вообще непонятно, как она будет выглядеть и какие параметры она имеет. Координаты начального и конечного квадратиков?

**Comment by SaAnnka** [comment]
Сейчас можно нарисовать стартовые клеточки где угодно

**Comment by paulin-mipt** [comment]
В нулевом приближении -- пойдет :)
